//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BannerMaster
    {
        [Key]
        public int Bannerid { get; set; }
        [DisplayName("Banner Heading")]
        public string Banner_Heading { get; set; }
        [DisplayName("Banner Description")]
        public string Banner_Description { get; set; }
        [DisplayName("Banner Image")]
        public string Banner_Image { get; set; }
    }
}
