//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PropertyListingMaster
    {
        [Key]
        public int Listid { get; set; }
        [DisplayName("Property List Category")]
        public string Property_listcategory { get; set; }
        [DisplayName("Property Type")]
        public string Property_type { get; set; }
        [DisplayName("Price")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Property Name")]
        public string Name { get; set; }
        [DisplayName("Location")]
        public string Location { get; set; }
        [DisplayName("Building Area")]
        public Nullable<decimal> BuildingArea { get; set; }
        [DisplayName(" No. Of Bedroom")]
        public Nullable<int> Bedroom { get; set; }
        [DisplayName("No. Of Bathroom")]
        public Nullable<int> Bathroom { get; set; }
        [DisplayName("Property List Image")]
        public string PropertyList_Image { get; set; }
    }
}
