//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PropertyClientMaster
    {
        [Key]
        public int Clientid { get; set; }
        [DisplayName("Client Descriptionv")]
        public string Client_Descriptionv { get; set; }
        [DisplayName("Client Name")]
        public string Client_name { get; set; }
        [DisplayName("Client Profession")]
        public string Client_profession { get; set; }
        [DisplayName("Client Image")]
        public string Client_image { get; set; }
    }
}
