//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PropertyTypeMaster
    {
        [Key]
        public int Typeid { get; set; }
        [DisplayName("Property Category")]
        public string Property_category { get; set; }
        [DisplayName("Property Type")]
        public string Property_type { get; set; }
    }
}
