//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PropertyAgentMaster
    {
        [Key]
        public int Agentid { get; set; }
        [DisplayName("Agent Name")]
        public string Agent_name { get; set; }
        [DisplayName("Agent Designation")]
        public string Agent_designation { get; set; }
        [DisplayName("Agent Contact")]
        public Nullable<long> Agent_contact { get; set; }
        [DisplayName("Agent Email")]
        public string Agent_Email { get; set; }
        [DisplayName("Agent Facebook")]
        public string Agent_Facebook { get; set; }
        [DisplayName("Agent Twitter")]
        public string Agent_Twitter { get; set; }
        [DisplayName("Agent Instagram")]
        public string Agent_Instagram { get; set; }
        [DisplayName("Agent Image")]
        public string Agent_Image { get; set; }
    }
}
