//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBrealestateEntities1 : DbContext
    {
        public DBrealestateEntities1()
            : base("name=DBrealestateEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BannerMaster> BannerMasters { get; set; }
        public virtual DbSet<PerfectPropertyMaster> PerfectPropertyMasters { get; set; }
        public virtual DbSet<PropertyAgentMaster> PropertyAgentMasters { get; set; }
        public virtual DbSet<PropertyClientMaster> PropertyClientMasters { get; set; }
        public virtual DbSet<PropertyListingMaster> PropertyListingMasters { get; set; }
        public virtual DbSet<PropertyTypeMaster> PropertyTypeMasters { get; set; }
        public virtual DbSet<Signup> Signups { get; set; }
    }
}
