//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Signup
    {
        [Key]
        public int Userid { get; set; }
        [Required(ErrorMessage ="*")]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Contact")]
        public Nullable<long> Contact { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}
